{
 "title": "IAA Service Level",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "site", "label": "Site :", "query": "SHOW TAG VALUES WITH KEY = url" }
  ]
 },
 "panels": [
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "responseTime",
     "measurement": "responseTime",
     "query": "SELECT responseTime, success, timeOut FROM \"defaultPolicy\".\"responseTime\" WHERE (\"url\" = 'http://xpd.dok.intra.renault.fr/ping') AND $timeFilter",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$site$/" }
     ]
    },
    {
     "alias": "success",
     "measurement": "responseTime",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Service percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "measurement": "responseTime",
     "query": "SELECT \"success\" * 100 FROM \"responseTime\" WHERE (\"url\" =~ /^$site$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Last events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT \"app\", \"env\", \"message\", \"up\" FROM \"events\" WHERE (\"url\" =~ /^$site$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "app" ], "type": "field" }
      ],
      [
       { "params": [ "env" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ],
      [
       { "params": [ "up" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  }
 ]
}